version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results

  steps:
    - restore_cache:
        keys:
          - m2-{{ checksum "pom.xml" }}
          - m2- # used if checksum fails
